### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by yoser-alrawi** [LieberInstitute/dotdotdot#5]
Hi,
I am new to MATLAB and I have been trying to use the rnascope_mouse script. I tried using the raw image that was posted over here "Mouse2.czi" but I was still unable to run the code. What I did was that I downloaded the toolbox and put .czi image and associated .jpg images that I found in over here in the same folder as the toolbox. Then, I opened the rnascope_mouse.m script and changed the filename definition to the path that I was using and I did the same thing for the toolbox. Then I tried running the code but I kept getting errors with the input or with some parts of the script as shown in the screenshot.

<img width="1440" alt="Screen Shot 2020-07-22 at 11 37 56 PM" src="https://user-images.githubusercontent.com/67768092/88252757-f82a0f00-cc74-11ea-9911-d114dc45f1ed.png">

I am not sure whether there are some errors in the code or I am not doing things correctly.

**Comment by vjysd** [comment]
Hi Yoser,

Thank you for posting your issue. I suspect that you are executing the function rnascope_mouse.m instead of calling it. I suggest you try this and let me know if you're still having issues,

After navigating to the folder that has rnascope_mouse.m script, in the command window execute rnascope_mouse(YOUR_FILENAME_PATH, YOUR_TOOLBOX_PATH). Keep the first two commented lines that start with % as is. They are just for reference.

**Comment by yoser-alrawi** [comment]
Hi Vijay,
Thank you for the reply!
I have tried your suggestion and that helped but I was getting the following error :

"segmenting DAPI
Error using rnascope_mouse (line 52)
Error: This statement is incomplete."

Line 52 is "ch = eval(['img.',char(O(d))]); "

**Comment by yoser-alrawi** [comment]
An update: I was able to solve this issue by removing "%" at the beginning of line 20!

**Comment by vjysd** [comment]
Hi Yoser,

I'm glad it worked out.

**Comment by yoser-alrawi** [comment]
Thanks Vijay!
